name: Alex's blog
markdown: redcarpet
pygments: true

links:
  - title: Home
    url: /
  - title: Teaching
    url: /teaching
  - title: FP Intro
    url: http://f.cl.ly/items/3M2s460S2Z021J2S1T3i/01-intro.html

redcarpet:
  extensions: ['smart']
